version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4488:4488'
    environment:
      PRISMA_CONFIG: |
        port: 4488
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  prisma_test:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4499:4499'
    environment:
      PRISMA_CONFIG: |
        port: 4499
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            database: prisma_test
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
